// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Models;

namespace Test.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("NeedSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("IdAction");

                    b.ToTable("Action");

                    b.HasData(
                        new
                        {
                            IdAction = 1,
                            NeedSpecialEquipment = true,
                            StartTime = new DateTime(2021, 5, 11, 11, 49, 17, 102, DateTimeKind.Local).AddTicks(5594)
                        },
                        new
                        {
                            IdAction = 2,
                            NeedSpecialEquipment = false,
                            StartTime = new DateTime(2021, 5, 11, 11, 49, 17, 117, DateTimeKind.Local).AddTicks(3042)
                        });
                });

            modelBuilder.Entity("Test.Models.FireTruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SpecialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("IdFireTruck");

                    b.ToTable("FireTruck");

                    b.HasData(
                        new
                        {
                            IdFireTruck = 1,
                            OperationalNumber = "123",
                            SpecialEquipment = true
                        },
                        new
                        {
                            IdFireTruck = 2,
                            OperationalNumber = "124",
                            SpecialEquipment = false
                        });
                });

            modelBuilder.Entity("Test.Models.FireTruckAction", b =>
                {
                    b.Property<int>("IdFireTruckAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFireTruck")
                        .HasColumnType("int");

                    b.HasKey("IdFireTruckAction");

                    b.HasIndex("IdAction");

                    b.HasIndex("IdFireTruck");

                    b.ToTable("FireTruck_Action");

                    b.HasData(
                        new
                        {
                            IdFireTruckAction = 1,
                            AssignmentDate = new DateTime(2021, 5, 11, 11, 49, 17, 118, DateTimeKind.Local).AddTicks(1248),
                            IdAction = 1,
                            IdFireTruck = 1
                        });
                });

            modelBuilder.Entity("Test.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFirefighter");

                    b.ToTable("Firefighter");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            FirstName = "Alisa",
                            LastName = "Kotiun"
                        },
                        new
                        {
                            IdFirefighter = 2,
                            FirstName = "Ann",
                            LastName = "Kotiun"
                        });
                });

            modelBuilder.Entity("Test.Models.FirefighterAction", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.HasKey("IdFirefighter", "IdAction");

                    b.HasIndex("IdAction");

                    b.ToTable("Firefighter_Action");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            IdAction = 1
                        });
                });

            modelBuilder.Entity("Test.Models.FireTruckAction", b =>
                {
                    b.HasOne("Test.Models.Action", "Action")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Models.FireTruck", "FireTruck")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdFireTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("FireTruck");
                });

            modelBuilder.Entity("Test.Models.FirefighterAction", b =>
                {
                    b.HasOne("Test.Models.Action", "Action")
                        .WithMany("FirefighterActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Test.Models.Firefighter", "Firefighter")
                        .WithMany("FirefighterActions")
                        .HasForeignKey("IdFirefighter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("Test.Models.Action", b =>
                {
                    b.Navigation("FirefighterActions");

                    b.Navigation("FireTruckActions");
                });

            modelBuilder.Entity("Test.Models.FireTruck", b =>
                {
                    b.Navigation("FireTruckActions");
                });

            modelBuilder.Entity("Test.Models.Firefighter", b =>
                {
                    b.Navigation("FirefighterActions");
                });
#pragma warning restore 612, 618
        }
    }
}
